# Generated by Django 3.0.4 on 2021-04-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210416_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='title',
            field=models.TextField(max_length=25),
        ),
    ]
