# Generated by Django 3.0.4 on 2021-04-16 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210416_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_bid', to='auctions.AuctionListing'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_watchlist', to='auctions.AuctionListing'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
