# Generated by Django 3.0.4 on 2021-04-15 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.AuctionListing'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
