# Generated by Django 3.0.4 on 2021-04-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='owener',
            new_name='owner',
        ),
    ]
