# Generated by Django 3.0.4 on 2021-04-15 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210415_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.AuctionListing', unique=True),
        ),
    ]
