# Generated by Django 3.0.4 on 2021-04-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210415_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='itemID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.AuctionListing'),
        ),
    ]
